[tool.poetry]
name = "carrier-owl"
version = "0.0.1"
description = "An assistant for sending out personalized invitations."
authors = ["Lucas Connors <lucas@revolutiontech.ca>"]
license = "ISC"

[tool.poetry.dependencies]
python = "^3.6"
Django = "~2.0.1"
psycopg2 = "^2.7.3.2"
django-classbasedsettings = "^1.5.0"
dj-database-url = "^0.4.2"
social-auth-app-django = "^2.1.0"
google-api-python-client = "^1.6.5"
oauth2client = "^4.1"

[tool.poetry.dev-dependencies]
factory-boy = "^2.11.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
