[tool.poetry]
name = "carrier-owl"
version = "0.0.1"
description = "An assistant for sending out personalized invitations."
authors = ["Lucas Connors <lucas@revolutiontech.ca>"]
license = "ISC"

[tool.poetry.dependencies]
python = "^3.6"
Django = "~2.1.10"
django-classbasedsettings = "^1.5.0"
social-auth-app-django = "^3.1.0"
google-api-python-client = "^1.7.9"
oauth2client = "^4.1"
zappa = "^0.48.2"
zappa-django-utils = "^0.4.0"
django-s3-storage = "^0.12.5"

[tool.poetry.dev-dependencies]
factory-boy = "^2.12.0"
coverage = "^4.5"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
