[tool.poetry]
name = "carrier-owl"
version = "0.0.1"
description = "An assistant for sending out personalized invitations."
authors = ["Lucas Connors <lucas@revolutiontech.ca>"]
license = "ISC"

[tool.poetry.dependencies]
python = "^3.8"
Django = "~3.0"
social-auth-app-django = "^3.4.0"
google-api-python-client = "^1.8.4"
oauth2client = "^4.1"
zappa = "^0.51.0"
django-s3-storage = "^0.13.2"
python-dotenv = "^0.13.0"
django-s3-sqlite = "^0.0.3"
django-configurations = "^2.2"

[tool.poetry.dev-dependencies]
factory-boy = "^2.12.0"
coverage = "^5.1"
black = "^19.10b0"
pyupgrade = "^2.3"
isort = "^4.3.21"

[tool.isort]
# https://github.com/psf/black/blob/master/docs/compatible_configs.md#isort
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 88

[tool.black]
line-length = 88
target_version = ["py38"]

[build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.masonry.api"
