[tool.poetry]
name = "carrier-owl"
version = "0.0.1"
description = "An assistant for sending out personalized invitations."
authors = ["Lucas Connors <lucas@revolutiontech.ca>"]
license = "ISC"

[tool.poetry.dependencies]
python = "^3.6"
Django = "~2.2"
django-classbasedsettings = "^1.5.0"
social-auth-app-django = "^3.1.0"
google-api-python-client = "^1.8.0"
oauth2client = "^4.1"
zappa = "^0.51.0"
django-s3-storage = "^0.13.0"
python-dotenv = "^0.12.0"
django-s3-sqlite = "^0.0.2"

[tool.poetry.dev-dependencies]
factory-boy = "^2.12.0"
coverage = "^5.0"
black = {version = "^19.10b0",allow-prereleases = true}
pyupgrade = "^1.26"

[tool.black]
line-length = 88
target_version = ["py36"]

[build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.masonry.api"
