# Generated by Django 2.2.9 on 2020-01-13 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event", old_name="attendees", new_name="guests",
        ),
        migrations.RenameField(
            model_name="event", old_name="description", new_name="message",
        ),
        migrations.RenameField(
            model_name="event", old_name="summary", new_name="subject",
        ),
        migrations.RemoveField(model_name="event", name="location",),
    ]
