# Generated by Django 2.2.9 on 2020-01-13 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0002_event_remove_location_and_rename_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event", name="message", field=models.TextField(),
        ),
    ]
